services:
  proxy:
    image: 'nginx:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/conf.d/default.template
      - ./nginx-data/:/data
      - ./letsencrypt:/etc/letsencrypt
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    environment:
      DOMAIN: 'localhost'
  vaultwarden:
    image: vaultwarden/server:latest
    ports:
      - '8218:80'
    volumes:
      - ./vw-data:/data
    environment:
      DOMAIN: 'https://vw.localhost'
      SIGNUPS_ALLOWED: "true"
