# Redirect HTTP to HTTPS
server {
  # For older versions of nginx appended http2 to the listen line after ssl and remove `http2 on`
  listen 443 ssl;
  listen [::]:443 ssl;
  ssl_certificate /etc/nginx/certs/site-cert.pem;
  ssl_certificate_key /etc/nginx/certs/site-cert-key.pem;
  server_name vw.*;
  location / {
    proxy_pass http://vaultwarden:80;
  }
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  ssl_certificate /etc/nginx/certs/site-cert.pem;
  ssl_certificate_key /etc/nginx/certs/site-cert-key.pem;
  server_name blog.*;

  location / {
    root /data/www;
  }
}

server {
  listen 443 ssl default_server;
  listen [::]:443 ssl default_server;
  ssl_certificate /etc/nginx/certs/site-cert.pem;
  ssl_certificate_key /etc/nginx/certs/site-cert-key.pem;

  return 301 https://blog.$host$request_uri;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    access_log /var/log/nginx/reverse-access.log;
    error_log /var/log/nginx/reverse-error.log;

    return 301 https://$host$request_uri;
}

